---
spring.config.activate.on-profile: local
fanstore:
  cloud:
    gcp:
      project-id: dev-melon-ticket-project01
      credentials:
        location:
      storage:
        bucket: local-fanstore-upload-files

---
spring.config.activate.on-profile: dev
fanstore:
  cloud:
    gcp:
      project-id: dev-melon-ticket-project01
      credentials:
        location:
      storage:
        bucket: dev-fanstore-upload-files

---
spring.config.activate.on-profile: cbt
fanstore:
  cloud:
    gcp:
      project-id: prod-melon-ticket-project01
      credentials:
        location:
      storage:
        bucket: fanstore-upload-files
---
spring.config.activate.on-profile: prod
fanstore:
  cloud:
    gcp:
      project-id: prod-melon-ticket-project01
      credentials:
        location:
      storage:
        bucket: fanstore-upload-files
