---
spring.cloud.config.profile: local
fanstore:
  message:
    policy:
      retryCount: 3
      retryDelay: 1000
    mq:
      #      pubsub:
      kafka:
        username: kafka
        password: wxaj8wjCW2
        bootstrapAddress: localhost:9092
        protocol: SASL_PLAINTEXT

---
spring.config.activate.on-profile: dev
fanstore:
  message:
    policy:
      retryCount: 3
      retryDelay: 1000
    mq:
      #      pubsub:
      kafka:
        username: kafka
        password: wxaj8wjCW2
        bootstrapAddress: localhost:9092
        protocol: SASL_PLAINTEXT

---
spring.config.activate.on-profile: cbt
fanstore:
  message:
    policy:
      retryCount: 3
      retryDelay: 1000
    mq:
      #      pubsub:
      kafka:
        username: kafka
        password: wxaj8wjCW2
        bootstrapAddress: localhost:9092
        protocol: SASL_PLAINTEXT

---
spring.config.activate.on-profile: prod
fanstore:
  message:
    policy:
      retryCount: 3
      retryDelay: 1000
    mq:
      #      pubsub:
      kafka:
        username: kafka
        password: wxaj8wjCW2
        bootstrapAddress: localhost:9092
        protocol: SASL_PLAINTEXT
