---
spring.config.activate.on-profile: local
fanstore:
  cache:
    redis:
      master:
        host: localhost
        port: 6399

---
spring.config.activate.on-profile: dev
fanstore:
  cache:
    redis:
      master:
        host: redis-svc.redis
        port: 6379

---
spring.config.activate.on-profile: cbt
fanstore:
  cache:
    redis:
      master:
        host: localhost
        port: 6379
      slave:
        host: localhost
        port: 6380
      password: 9rWqhaZ8Ygdzhi3JA6ovPQ6zn9arFuGiXECjceprb5ey9xJWbXPjgYAzLoRZA4gGWD7W7AcBvZBG1bYLdvSS6Zm3KKfqgQmy4LQ93TtmQ55mmUHate1vymwHiiKM6fdz

---
spring.config.activate.on-profile: prod
fanstore:
  cache:
    redis:
      master:
        host: localhost
        port: 6379
      slave:
        host: localhost
        port: 6380
      password: 9rWqhaZ8Ygdzhi3JA6ovPQ6zn9arFuGiXECjceprb5ey9xJWbXPjgYAzLoRZA4gGWD7W7AcBvZBG1bYLdvSS6Zm3KKfqgQmy4LQ93TtmQ55mmUHate1vymwHiiKM6fdz
