fanstore:
  message:
    policy:
      retryCount: 3
      retryDelay: 1000
    mq:
      #      pubsub:
      kafka:
        username: kafka-prod
        password: wxaj8wjCW2
        bootstrapAddress: localhost:9092
        protocol: SASL_PLAINTEXT
